name: release whl

on:
  push:
    branches:
      - master
    paths:
      - 'wawbus/__meta__.py'  # if version bump
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Build whl
        run: |
          make build
      - name: Get version
        id: get_version
        run: |
          echo "::set-output name=version::$(python3 -c 'import wawbus; print(wawbus.__version__)')"
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.get_version.outputs.version }}
          prerelease: false
          title: ${{ steps.get_version.outputs.version }}
          files: dist/*.whl
          overwrite: true